// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IhDwhZtzAkN4AndOP-TzzcDOntzaAIw',
    appId: '1:444252860325:web:9d7a0eabdb5ad5056e824c',
    messagingSenderId: '444252860325',
    projectId: 'societiesapp-992a8',
    authDomain: 'societiesapp-992a8.firebaseapp.com',
    storageBucket: 'societiesapp-992a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3fDXwxtrc8W8v9mgv60Njuw5YbGGLpE',
    appId: '1:444252860325:android:9a0281b8aa0e33126e824c',
    messagingSenderId: '444252860325',
    projectId: 'societiesapp-992a8',
    storageBucket: 'societiesapp-992a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqOcDLZY3h3VlhL73fi_qe97fg-YmvhQ',
    appId: '1:444252860325:ios:7b377c34abbd2dc16e824c',
    messagingSenderId: '444252860325',
    projectId: 'societiesapp-992a8',
    storageBucket: 'societiesapp-992a8.appspot.com',
    iosBundleId: 'com.example.testApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqOcDLZY3h3VlhL73fi_qe97fg-YmvhQ',
    appId: '1:444252860325:ios:7d1875ae5f7832916e824c',
    messagingSenderId: '444252860325',
    projectId: 'societiesapp-992a8',
    storageBucket: 'societiesapp-992a8.appspot.com',
    iosBundleId: 'com.example.testApp2.RunnerTests',
  );
}
